name: CMake Build Matrix

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: gcc

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up Ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Configure CMake
        run: cmake -S . -B build -G Ninja

      - name: Build
        run: cmake --build build

      - name: List build directory
        run: |
          echo "Contents of build directory:"
          ls build || dir build

      - name: Run HelloWorld
        run: |
          echo "Searching for HelloWorld executable..."
          find . -type f -name "HelloWorld*" -exec echo "Found: {}" \; -exec {} \; || echo "Executable not found or failed to run"
