name: CMake Build Matrix

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake ninja-build ${{ matrix.compiler }}

    - name: Debug Info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Compiler: ${{ matrix.compiler }}"

    - name: Configure CMake
      run: cmake -S . -B build -G Ninja -DCMAKE_C_COMPILER=${{ matrix.compiler }}

    - name: Build
      run: cmake --build build

    - name: Run HelloWorld
      run: ./build/HelloWorld
